# Markdown linting configuration
default: true

# Line length and code blocks
MD013: false

# No hard tabs
MD010: false

# No trailing spaces
MD009: false

# No multiple spaces
MD018: false
MD019: false

# No multiple headers with the same content
MD024:
  siblings_only: true

# No multiple spaces after list marker
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# List item indentation
MD007:
  indent: 2

# Unordered list style
MD004:
  style: asterisk

# Ordered list item prefix
MD029: false

# Allow inline HTML
MD033: false

# Allow emphasis used for header
MD036: false

# Allow bare URLs
MD034: false

# Allow fenced code blocks without language
MD040: false

# Allow first line not being a heading
MD041: false
