---
# tfsec configuration file
# This file allows you to customize tfsec behavior

# Minimum version of tfsec to use
minimum_version: 1.0.0

# Custom checks (optional)
# custom_checks:
#   - code: CUSTOM001
#     description: "Custom check description"
#     required_types: ["resource"]
#     required_labels: ["aws_instance"]
#     severity: "ERROR"
#     match:
#       - "resource \"aws_instance\" \"example\" {"

# Exclude specific checks (optional)
# exclusions:
#   - "AWS018"  # Ensure security group rule descriptions
#   - "AWS017"  # Ensure all data stored in the S3 bucket is securely encrypted at rest

# Soft fails (warnings instead of errors)
# soft_fails:
#   - "AWS018"  # Treat AWS018 as warning instead of error

# Workspace settings
workspace_settings:
  # Enable/disable specific workspaces
  # enabled_workspaces:
  #   - "default"
  #   - "production"

# Output settings
output_settings:
  # Output format (json, sarif, text, csv)
  format: "sarif"
  
  # Include passed checks in output
  include_passed: false
  
  # Include ignored checks in output
  include_ignored: false

# Severity levels
severity_levels:
  # Minimum severity to report
  minimum_severity: "LOW"
  
  # Severity mapping
  severity_mapping:
    CRITICAL: "ERROR"
    HIGH: "ERROR"
    MEDIUM: "WARNING"
    LOW: "INFO"

# Timeout settings
timeout_settings:
  # Maximum time to wait for tfsec to complete
  timeout: "300s"
  
  # Timeout for individual checks
  check_timeout: "30s" 